name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_BACK: laipuni/cps-platform:back
  DOCKER_IMAGE_FRONT: laipuni/cps-platform:front

jobs:
  deploy:
    name: Build & Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          cat <<EOF > ./back/.env
          SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_REDIS_HOST=${{ secrets.SPRING_REDIS_HOST }}
          SPRING_REDIS_PORT=${{ secrets.SPRING_REDIS_PORT }}
          SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}
          AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_S3_SECRET_KEY=${{ secrets.AWS_S3_SECRET_KEY }}
          AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
          REGISTER_ENCODER_SECRETKEY=${{ secrets.REGISTER_ENCODER_SECRETKEY }}
          EOF
      
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & tag with docker-compose
        run: |
          docker-compose -f docker-prod.yml build
          docker tag creative-contest-manager-web-backend $DOCKER_IMAGE_BACK
          docker tag creative-contest-manager-web-frontend $DOCKER_IMAGE_FRON

      - name: Push with docker
        run: |
          docker push $DOCKER_IMAGE_BACK
          docker push $DOCKER_IMAGE_FRONT
          
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/your-app-directory
            docker-compose pull
            docker-compose up -d
